version: '3.8'

services:
  frontend:
    image: minorprojectpsychetrack-frontend:latest
    ports:
      - "3000:3000"  # Adjust port as needed
    networks:
      - psychetrack_network

  backend:
    image: minorprojectpsychetrack-backend:latest
    ports:
      - "8000:8000"  # Adjust port as needed
    networks:
      - psychetrack_network

networks:
  psychetrack_network:
    driver: bridge
